### ISSUE TITLE
about the BLue and  ROUGE-L

### ISSUE THREAD

**Issue by ToneLi** [allenai/openpi-dataset#15]
So sorry to bother you, I just want to make sure, in your paper, you used Bleu-2 right? the score[1] refers to the BLeu2,  and the ROUGE version is ROUGE-L
    def compute_score(self, gold: str, predicted: str):
        # Reference: gold , Hypothesis: predicted
        print("--------------ddd")
        score, score_info = self.metric.compute_score(
            gts={0: [normalize_and_stem(gold)]},
            res={0: [normalize_and_stem(predicted)]}
        )
        return score[1]/100.0

**Comment by nikett** [comment]
Yes, that's right. Bleu-2
