### ISSUE TITLE
Will the code for training be released?

### ISSUE THREAD

**Issue by RunxinXu** [allenai/openpi-dataset#2]
Nice work !! 
Will the code for training be released?
Thanks:)

**Comment by nikett** [comment]
Yes, all the data has been released: https://github.com/allenai/openpi-dataset/tree/main/data/gold

**Comment by RunxinXu** [comment]
Sorry, I mean the code, not the data :)

**Comment by nikett** [comment]
The code for evaluation is released. The baseline that is reported in the paper is GPT2 from huggingface transformers. Since it is a straightforward plug and play, and would bloat up the repo (that's intended for data)-- we didn't include it.

**Comment by nikett** [comment]
Training, prediction of the GPT2 model used in the paper; and the evaluation code-- is all now included. Please raise an issue if you face any problem.
