### ISSUE TITLE
May raise an error "expected str, bytes or os.PathLike object, not NoneType" if "continue_from_dir" is not defined

### ISSUE THREAD

**Issue by zhanghaotong1** [allenai/openpi-dataset#5]
_continue_from_dir_ is not required and if not defined, the default result is None. This may cause an issue during training when line 395 in **run_trainer.py** calls function **train** and line 248 in **trainer.py** 
_glob_checkpoints = glob.glob(os.path.join(args.continue_from_dir, "{}-*".format(checkpoint_prefix)))_  
will raise an error _expected str, bytes or os.PathLike object, not NoneType_.

This could be solved to assign _continue_from_dir_ = _output_dir_ if does not have pretrained checkpoints.

**Comment by nikett** [comment]
Hi Zhang, did this happen when you were trying "distributed training"?

**Comment by nikett** [comment]
Fixed: https://github.com/allenai/openpi-dataset/commit/452ac571e00e0f541d4990c187b3da0a221a6d2e
