### ISSUE TITLE
"RuntimeError: The size of tensor a (1024) must match the size of tensor b (1025) at non-singleton dimension 3" when using generation.py

### ISSUE THREAD

**Issue by zhanghaotong1** [allenai/openpi-dataset#6]
Sometimes, **generation.py** may raise an error 
_RuntimeError: The size of tensor a (1024) must match the size of tensor b (1025) at non-singleton dimension 3_ 
If you are sure that the format of your data is correct, then it may because that the input sequence is longer than the maximum input sequence length (1024). This can be avoided by editing **line 102** in **generation.py** to 
_max_length=min(1024,max_len + encoded_prompt.size(-1)),_

**Comment by dheerajrajagopal** [comment]
Thank you so much for pointing it out, and I was able to reproduce this error at our end too. The generation code of GPT2 does limit the tokens to 1024. Please feel free to submit a PR and we can then merge it to the master.

**Comment by nikett** [comment]
PR merged. Thanks Haotong!
